version: '3.8'

services:
  mern_app: 
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: product_store_image  
    ports:
      - "5000:5000"  
    hostname: talha 
    container_name: prodcut_store
